name: Deploy Docker image to GHCR

on:
  push:
    branches:
      - main
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Login to GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.ACCESS_TOKEN}}

      - name: 'Build and push image'
        run: |
          docker build . --tag ghcr.io/iztokbajcar/luanti:latest
          docker push ghcr.io/iztokbajcar/luanti:latest

