name: Deploy Docker image to GHCR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Luanti version"
        required: false
        default: "latest"
  push:
    branches:
      - main
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Login to GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.ACCESS_TOKEN}}

      - name: 'Determine Luanti version to build'
        id: version
        run: |
          IMAGE_TAG_NAME=latest
          BUILD_VERSION=""
          if [ -n "${{github.events.inputs.version}}" ]; then
            BUILD_VERSION="${{github.events.inputs.version}}"
            IMAGE_TAG_NAME="$PROVIDED_VERSION"
          else
            LATEST_TAG=$(curl -sL https://api.github.com/repos/luanti-org/luanti/releases/latest | jq -r '.tag_name')
            BUILD_VERSION="$LATEST_TAG"
            echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
          fi

          echo "Will build version $BUILD_VERSION"
          echo "Tag: $IMAGE_TAG_NAME"

          echo "version=$BUILD_VERSION" >> $GITHUB_OUTPUT
          echo "image_tag_name=$IMAGE_TAG_NAME" >> $GITHUB_OUTPUT

      - name: 'Build and push image'
        run: |
          docker build --build-arg VERSION=${{steps.version.outputs.version}} --tag ghcr.io/iztokbajcar/luanti:${{steps.version.outputs.image_tag_name}} .
          docker push ghcr.io/iztokbajcar/luanti:${{steps.version.outputs.image_tag_name}}

