name: Deploy Docker image to GHCR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Luanti version"
        required: true
        default: "5.14"
  push:
    branches:
      - main
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Login to GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.ACCESS_TOKEN}}

      - name: 'Build and push image'
        run: |
          docker build --build-arg VERSION=${{github.event.inputs.version}} --tag ghcr.io/iztokbajcar/luanti:${{github.event.inputs.version}} .
          docker push ghcr.io/iztokbajcar/luanti:${{github.events.inputs.version}}

